# Generated by Django 2.2.12 on 2020-07-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='优惠码')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='折扣')),
                ('is_effective', models.BooleanField(default=1, verbose_name='是否有效')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('order_status', models.IntegerField(choices=[(-1, '交易取消'), (0, '等待付款'), (1, '未发货'), (2, '已发货'), (3, '已完成')], default=0, verbose_name='订单状态')),
                ('order_completion_time', models.DateTimeField(null=True, verbose_name='订单完成时间')),
                ('payment_method', models.IntegerField(choices=[(0, '支付宝'), (1, '微信')], default=0, verbose_name='支付方式')),
                ('shipping_address', models.CharField(max_length=100, null=True, verbose_name='收货地址')),
                ('user_reviews', models.CharField(max_length=300, null=True, verbose_name='用户评价')),
                ('store_reply', models.CharField(max_length=300, null=True, verbose_name='商家回评')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50, verbose_name='宠物名')),
                ('p_describe', models.CharField(default='暂无描述', max_length=300, verbose_name='宠物描述')),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='宠物价格')),
                ('p_image', models.ImageField(null=True, upload_to='', verbose_name='宠物照片')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='宠物类别')),
            ],
        ),
        migrations.CreateModel(
            name='PetProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_name', models.CharField(max_length=50, unique=True, verbose_name='商品名称')),
                ('pp_descripe', models.CharField(default='暂无描述', max_length=200, verbose_name='商品描述')),
                ('pp_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('pp_quantity', models.IntegerField(verbose_name='库存数量')),
                ('pp_image_path', models.ImageField(null=True, upload_to='', verbose_name='商品图片')),
                ('is_featured_products', models.BooleanField(default=0, verbose_name='特色产品')),
                ('pet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PetCategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserCartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('pet_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PetProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PetProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='PetVariety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_name', models.CharField(max_length=50, unique=True, verbose_name='宠物品种')),
                ('foster_daily_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='寄养价格/天')),
                ('pet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PetCategory')),
            ],
        ),
        migrations.CreateModel(
            name='PetFosterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='寄养数量')),
                ('start_date', models.DateField(verbose_name='寄养开始日期')),
                ('end_date', models.DateField(verbose_name='寄养结束日期')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
                ('pet_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PetVariety')),
            ],
        ),
        migrations.CreateModel(
            name='PetFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PetVariety'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_quantity', models.IntegerField(verbose_name='购买数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
                ('pet_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PetProduct')),
            ],
        ),
    ]
