# Generated by Django 2.2.12 on 2020-07-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_content', models.CharField(max_length=300, verbose_name='全站消息内容')),
                ('sn_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='手机号')),
                ('register_time', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='邮箱')),
                ('real_name', models.CharField(max_length=50, null=True, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=50, null=True, verbose_name='身份证')),
                ('sex', models.CharField(choices=[('m', '男'), ('f', '女'), ('o', '其他')], default='m', max_length=50, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('last_login_time', models.DateTimeField(null=True, verbose_name='上次登录时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=300, verbose_name='反馈内容')),
                ('feedback_time', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('store_reply', models.CharField(max_length=300, null=True, verbose_name='店家回复')),
                ('reply_time', models.DateTimeField(null=True, verbose_name='回复时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='收货人')),
                ('address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('postcode', models.CharField(max_length=50, null=True, verbose_name='邮编')),
                ('receiver_phone_number', models.CharField(max_length=50, verbose_name='收货人手机号')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_content', models.CharField(max_length=300, verbose_name='消息内容')),
                ('m_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('m_status', models.BooleanField(default=0, verbose_name='已读/未读')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
